# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

kde2dCpp <- function(x, y, xo, yo, limx, limy, bwv, area) {
    .Call('_kdeR_kde2dCpp', PACKAGE = 'kdeR', x, y, xo, yo, limx, limy, bwv, area)
}

